name: DBNet_lsvt_border2_thred_fintune
base: ['config/lsvt_mini_border2.yaml']
arch:
  type: Model
  is_binary: True
  is_thred: True
  backbone:
    type: resnet18
    pretrained: true
  neck:
    type: FPN
    inner_channels: 256
  head:
    type: DBHead
    out_channels: 2
    k: 50
post_processing:
  type: SegDetectorRepresenter
  args:
    thresh: 0.3
    box_thresh: 0.7
    max_candidates: 1000
    unclip_ratio: 1.5 # from paper
metric:
  type: QuadMetric
  args:
    is_output_polygon: false
loss:
  type: DBLoss
  alpha: 1
  beta: 10
  ohem_ratio: 3
optimizer:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0
    amsgrad: true
lr_scheduler:
  type: WarmupPolyLR
  args:
    warmup_epoch: 0
trainer:
  seed: 2
  epochs: 120
  log_iter: 1
  show_images_iter: 50
  #  resume_checkpoint: 'output/DBNet_lsvt_border2_thred_resnet18_FPN_DBHead/checkpoint/model_latest.pth'
  resume_checkpoint: ''
  finetune_checkpoint: 'output/DBNet_lsvt_border2_thred_fintune_resnet18_FPN_DBHead/checkpoint/model_latest.pth'
  output_dir: output
  tensorboard: False
dataset:
  train:
    dataset:
      args:
        data_path:
          - ../datasets/opensource/LSVT/db/train_1000.txt
        img_mode: RGB
    loader:
      batch_size: 1
      shuffle: False
      pin_memory: true
      num_workers: 1
      collate_fn: ''
  validate:
    dataset:
      args:
        data_path:
          - ../datasets/opensource/LSVT/db/test_200.txt
        pre_processes:
          - type: ResizeShortSize
            args:
              short_size: 736
              resize_text_polys: false
        img_mode: RGB
    loader:
      batch_size: 1
      shuffle: False
      pin_memory: false
      num_workers: 16
      collate_fn: ICDARCollectFN
